### PR TITLE
Fixed the conflicts

### PR DESCRIPTION
**Pull request by ninjagolloyd**
There were weird conflicts on the other request, so here you go. I feel like since the website has a demo, it should show the syntax.

### CODE REVIEW

**Comment by alyssarosenzweig** [comment]
Beautiful :heart:

**Comment by ninjagolloyd** [comment]
:grinning:  first time I have EVER heard that on github

**Comment by alyssarosenzweig** [comment]
@ninjagolloyd Just cleaning things a few things up, and it will be live soon :)

**Comment by ninjagolloyd** [comment]
Yay!

**Comment by alyssarosenzweig** [comment]
Done!

**Pull request merged**
