### PR TITLE
ul/li lists

### PR DESCRIPTION
**Pull request by alyssarosenzweig**

### CODE REVIEW

**Comment by kach** [comment]
Ummm the list of `<li>` tags needs to be wrapped in a `<ul>`:

```
<ul>
<li>Something
<li>Something else
<li> More something
</ul>
```

You can probably cheat by wrapping _all_ slide contents (past the header) in a `<ul>`, since I'll probably use lists for 98% of the slides anyway.

**Comment by alyssarosenzweig** [comment]
@Hardmath123 Better?

**Comment by kach** [comment]
> all slide contents _(past the header)_

```
…
        <ul>
            <h1> Purpose</h1>
            <li>When people first learn to code, simple Hello, World program</li>
            <li class='alt'>Can also be used to test the capabilities of a language</li>
        </ul>
…
```

Such a hack!

Can you instead change the grammar and add a `list` nonterminal under `marker` which expands to something like `("~" lphrase):*` or something? Then you can do this _properly_. :P

**Comment by alyssarosenzweig** [comment]
@Hardmath123 How would this help?

**Comment by kach** [comment]
So that you can mix paragraphs and lists. So you can do something like:

```
A sheep is a kind of animal. It has:
~ A tail
~ Lots of wool
I like sheep because:
~ They're cute
~ They eat baobabs
```

And it compiles to

``` html
<p>A sheep is a kind of animal. It has:</p>
<ul>
<li>A tail</li>
<li>Lots of wool</li>
</ul>
<p>I like sheep because:</p>
<ul>
<li>They're cute</li>
<li>They eat baobabs</li>
</ul>
```

Also, fwiw, I don't care _too_ much about nested lists, so that's low-priority for now.

**Pull request merged**
