### PR TITLE
Feature/slide transitions

### PR DESCRIPTION
**Pull request by alyssarosenzweig**

### CODE REVIEW

**Comment by kach** [comment]
Nice job! My only feedback is that you should check if the slide number is below zero or above the number of slides, and prevent it from trying to go to slide -4 or slide 2346827346 if you hold down a key.

**Comment by alyssarosenzweig** [comment]
@Hardmath123 How do you propose to be the cleanest way to find out the biggest slide number?

Either inline JS injected by nearley or DOM hacks are the two ways I can think of, but they both seem bad... thoughts?

**Comment by kach** [comment]
```
if (!document.getElementById(your-computed-slide-id)) {
    don't switch
} else {
    switch, advance counter, etc.
}
```

Just checks if the slide exists. :-)

**Comment by alyssarosenzweig** [comment]
@Hardmath123 Better?

**Comment by kach** [comment]
Ummm

```
$ node publish.js test.up -o test.html 
publish.js:42
res[1].forEach(function(slide, n) {
       ^
TypeError: undefined is not a function
```

**Comment by kach** [comment]
Never mind, git borking on my end.

:+1: I like it.

**Pull request merged**
